-- 004_seed.sql
-- Tiny REFERENCE dataset so the API returns rows immediately after
-- `docker compose up` even before `make seed`. The bulk deterministic
-- datasets (small/medium/large) are generated by scripts/seed.py.
--
-- Seed accounts are NON-LOGIN demo rows: password_hash is a placeholder.

INSERT INTO users (id, username, email, password_hash) VALUES
    (1,  'ada_lovelace',  'ada@example.test',  'seed-no-login'),
    (2,  'alan_turing',   'alan@example.test', 'seed-no-login'),
    (3,  'grace_hopper',  'grace@example.test','seed-no-login'),
    (4,  'linus_t',       'linus@example.test','seed-no-login'),
    (5,  'margaret_h',    'margaret@example.test','seed-no-login'),
    (6,  'dennis_r',      'dennis@example.test','seed-no-login'),
    (7,  'katherine_j',   'katherine@example.test','seed-no-login'),
    (8,  'norman_ab',     'norman@example.test','seed-no-login'),
    (9,  'radia_p',       'radia@example.test','seed-no-login'),
    (10, 'barbara_l',     'barbara@example.test','seed-no-login'),
    (11, 'edsger_d',      'edsger@example.test','seed-no-login'),
    (12, 'donald_k',      'donald@example.test','seed-no-login'),
    (13, 'ken_t',         'ken@example.test',  'seed-no-login'),
    (14, 'frances_a',     'frances@example.test','seed-no-login'),
    (15, 'ivan_s',        'ivan@example.test', 'seed-no-login'),
    (16, 'vint_c',        'vint@example.test', 'seed-no-login'),
    (17, 'tim_b',         'tim@example.test',  'seed-no-login'),
    (18, 'sally_f',       'sally@example.test','seed-no-login'),
    (19, 'guido_vr',      'guido@example.test','seed-no-login'),
    (20, 'brendan_e',     'brendan@example.test','seed-no-login')
ON CONFLICT (id) DO NOTHING;

SELECT setval(pg_get_serial_sequence('users', 'id'), GREATEST((SELECT max(id) FROM users), 1), true);

INSERT INTO profiles (id, user_id, display_name, bio) VALUES
    (1,  1,  'Ada Lovelace',  'First programmer. Analytical engines and poetry.'),
    (2,  2,  'Alan Turing',   'Enigma breaker, Turing Award namesake.'),
    (3,  3,  'Grace Hopper',  'Compilers, COBOL, nanoseconds.'),
    (4,  4,  'Linus Torvalds','Linux and git.'),
    (5,  5,  'Margaret Hamilton','Software engineering, Apollo.'),
    (6,  6,  'Dennis Ritchie','C and Unix.'),
    (7,  7,  'Katherine Johnson','Orbital mechanics.'),
    (8,  8,  'Norman Abramson','ALOHAnet.'),
    (9,  9,  'Radia Perlman', 'Spanning tree.'),
    (10, 10, 'Barbara Liskov','Abstraction and CLU.'),
    (11, 11, 'Edsger Dijkstra','Algorithms and rigor.'),
    (12, 12, 'Donald Knuth',  'The Art of Computer Programming.'),
    (13, 13, 'Ken Thompson',  'Unix and B.'),
    (14, 14, 'Frances Allen', 'Optimizing compilers.'),
    (15, 15, 'Ivan Sutherland','Computer graphics.'),
    (16, 16, 'Vint Cerf',     'TCP/IP.'),
    (17, 17, 'Tim Berners-Lee','The Web.'),
    (18, 18, 'Sally Floyd',   'Congestion control.'),
    (19, 19, 'Guido van Rossum','Python.'),
    (20, 20, 'Brendan Eich',  'JavaScript.')
ON CONFLICT (id) DO NOTHING;

SELECT setval(pg_get_serial_sequence('profiles', 'id'), GREATEST((SELECT max(id) FROM profiles), 1), true);

INSERT INTO media (id, owner_id, storage_key, media_type, mime_type, size_bytes) VALUES
    (1, 1, 'haystack-inspired/avatars/ada.jpg',    'image', 'image/jpeg', 48213),
    (2, 2, 'haystack-inspired/avatars/alan.jpg',   'image', 'image/jpeg', 51201),
    (3, 3, 'haystack-inspired/avatars/grace.jpg',  'image', 'image/jpeg', 39876),
    (4, 12, 'haystack-inspired/docs/tao-vol1.pdf',  'document','application/pdf', 824112)
ON CONFLICT (id) DO NOTHING;

SELECT setval(pg_get_serial_sequence('media', 'id'), GREATEST((SELECT max(id) FROM media), 1), true);

-- Posts are key-aligned-friendly in sharded mode only when inserted through
-- the application; reference rows are for the NORMALIZED first-boot DB.
INSERT INTO posts (id, author_id, content, visibility) VALUES
    (1, 1,  'The Analytical Engine weaves algebraic patterns.', 'public'),
    (2, 2,  'Sometimes it is the people no one imagines anything of.', 'public'),
    (3, 3,  'A ship in port is safe, but that is not what ships are for.', 'public'),
    (4, 4,  'Talk is cheap. Show me the code.', 'public'),
    (5, 12,'Premature optimization is the root of all evil.', 'public'),
    (6, 6,  'Simplicity and elegance go together.', 'public'),
    (7, 9,  'The world does not need another spanning tree — mine floods.', 'public'),
    (8, 17,'The web does not belong to me — it belongs to everyone.', 'public'),
    (9, 19,'Readability counts.', 'public'),
    (10, 10,'Programming is about abstraction.', 'followers'),
    (11, 11,'Testing shows the presence, not the absence of bugs.', 'public'),
    (12, 15,'The display is the window into the computer.', 'public')
ON CONFLICT (id) DO NOTHING;

SELECT setval(pg_get_serial_sequence('posts', 'id'), GREATEST((SELECT max(id) FROM posts), 1), true);

INSERT INTO comments (id, post_id, user_id, content) VALUES
    (1, 1, 3, 'Poetry and mathematics together.'),
    (2, 1, 9, 'Way ahead of her time.'),
    (3, 2, 5, 'Still inspiring.'),
    (4, 4, 12,'Amen.'),
    (5, 5, 11,'Context matters, though.'),
    (6, 5, 19,'Readability counts too.'),
    (7, 8, 16,'Universal.'),
    (8, 9, 20,'import this'),
    (9, 11, 6,'Both are useful mindsets.'),
    (10, 3, 2,'Go for it.')
ON CONFLICT (id) DO NOTHING;

SELECT setval(pg_get_serial_sequence('comments', 'id'), GREATEST((SELECT max(id) FROM comments), 1), true);

INSERT INTO likes (id, post_id, user_id) VALUES
    (1, 1, 2), (2, 1, 3), (3, 1, 5),
    (4, 2, 1), (5, 2, 3),
    (6, 3, 2), (7, 3, 5),
    (8, 4, 6), (9, 4, 12), (10, 4, 19),
    (11, 5, 4), (12, 5, 11),
    (13, 8, 16), (14, 8, 19), (15, 8, 20),
    (16, 9, 12), (17, 9, 4)
ON CONFLICT (id) DO NOTHING;

SELECT setval(pg_get_serial_sequence('likes', 'id'), GREATEST((SELECT max(id) FROM likes), 1), true);

INSERT INTO follows (follower_id, following_id) VALUES
    (1, 2), (2, 1), (3, 1), (4, 12), (5, 2), (6, 4),
    (9, 10), (10, 9), (12, 4), (12, 19), (16, 17),
    (17, 16), (19, 12), (20, 19), (11, 12), (6, 12)
ON CONFLICT DO NOTHING;

INSERT INTO notifications (id, recipient_id, actor_id, type, reference_id, is_read) VALUES
    (1, 1, 2, 'like', 1, FALSE),
    (2, 1, 3, 'follow', NULL, FALSE),
    (3, 4, 12, 'like', 4, TRUE),
    (4, 12, 19, 'like', 5, FALSE),
    (5, 17, 16, 'follow', NULL, TRUE),
    (6, 2, 5, 'comment', 3, FALSE)
ON CONFLICT (id) DO NOTHING;

SELECT setval(pg_get_serial_sequence('notifications', 'id'), GREATEST((SELECT max(id) FROM notifications), 1), true);
