"""Initialize shard databases and/or (re)generate shard init-SQL.

Two modes:

* default (no flags): connect to every SHARD_n_URL, create the canonical
  schema on each independent PostgreSQL shard, and optionally on the canonical
  DATABASE_URL when --canonical is passed.

* ``--write-sql``: derive the shard DDL directly from the shared SQLAlchemy
  models (single source of truth) and write it into
  infrastructure/postgres/shards/shard-N/ for Docker first-boot.
"""

from __future__ import annotations

import argparse
import asyncio
import sys
from pathlib import Path

_ROOT = Path(__file__).resolve().parent.parent
sys.path.insert(0, str(_ROOT))
sys.path.insert(0, str(_ROOT / "packages"))
sys.path.insert(0, str(_ROOT / "services" / "shard-router"))
sys.path.insert(0, str(_ROOT / "apps"))

from common.config import get_settings  # noqa: E402
from db.engine import build_connect_args  # noqa: E402
from models import Base  # noqa: E402
from sqlalchemy.ext.asyncio import create_async_engine  # noqa: E402
from sqlalchemy.schema import CreateIndex, CreateTable  # noqa: E402

SHARD_COUNT = 4
HEADER = """-- AUTO-GENERATED by scripts/initialize_shards.py --write-sql
-- Source of truth: packages/models (SQLAlchemy 2.0 models).
-- Do not edit by hand; shards carry the SAME relational schema as canonical.
"""


def render_ddl() -> str:
    statements: list[str] = [HEADER]
    tables = sorted(Base.metadata.sorted_tables, key=lambda t: t.name)
    for table in tables:
        statements.append(str(CreateTable(table).compile(dialect=_pg_dialect())).strip() + ";")
    for table in tables:
        for index in table.indexes:
            statements.append(str(CreateIndex(index).compile(dialect=_pg_dialect())).strip() + ";")
    return "\n\n".join(statements) + "\n"


def _pg_dialect():
    from sqlalchemy.dialects import postgresql

    return postgresql.dialect()


def write_sql(shards_dir: Path, shard_count: int = SHARD_COUNT) -> list[Path]:
    ddl = render_ddl()
    written: list[Path] = []
    for i in range(shard_count):
        d = shards_dir / f"shard-{i}"
        d.mkdir(parents=True, exist_ok=True)
        target = d / "001_schema.sql"
        target.write_text(ddl, encoding="utf-8")
        written.append(target)
    return written


async def init_database(url: str, name: str) -> None:
    settings = get_settings()
    engine = create_async_engine(url, pool_pre_ping=True, connect_args=build_connect_args(settings))
    try:
        async with engine.begin() as conn:
            await conn.run_sync(Base.metadata.create_all)
        print(f"  initialized schema on {name}")
    finally:
        await engine.dispose()


async def main() -> None:
    parser = argparse.ArgumentParser(description="Initialize MetaScale shards")
    parser.add_argument(
        "--write-sql", action="store_true", help="regenerate per-shard init SQL from models"
    )
    parser.add_argument(
        "--canonical", action="store_true", help="also initialize DATABASE_URL (canonical instance)"
    )
    parser.add_argument("--shard-count", type=int, default=SHARD_COUNT)
    args = parser.parse_args()

    shards_dir = _ROOT / "infrastructure" / "postgres" / "shards"
    if args.write_sql:
        files = write_sql(shards_dir, args.shard_count)
        print(f"wrote {len(files)} shard schema files:")
        for f in files:
            print(" ", f.relative_to(_ROOT))

    urls = get_settings().shard_urls()
    if urls:
        print(f"creating schema on {len(urls)} live shards...")
        for sid, url in list(urls.items())[: args.shard_count]:
            await init_database(url, sid)
    elif not args.write_sql:
        print("No SHARD_n_URL configured; nothing to initialize live.")

    if args.canonical:
        await init_database(get_settings().database_url, "canonical")


if __name__ == "__main__":
    asyncio.run(main())
