-- AUTO-GENERATED by scripts/initialize_shards.py --write-sql
-- Source of truth: packages/models (SQLAlchemy 2.0 models).
-- Do not edit by hand; shards carry the SAME relational schema as canonical.


CREATE TABLE comments (
	id BIGSERIAL NOT NULL, 
	post_id BIGINT NOT NULL, 
	user_id BIGINT NOT NULL, 
	content TEXT NOT NULL, 
	created_at TIMESTAMP WITH TIME ZONE DEFAULT now() NOT NULL, 
	PRIMARY KEY (id), 
	FOREIGN KEY(post_id) REFERENCES posts (id) ON DELETE CASCADE
);

CREATE TABLE follows (
	follower_id BIGINT NOT NULL, 
	following_id BIGINT NOT NULL, 
	created_at TIMESTAMP WITH TIME ZONE DEFAULT now() NOT NULL, 
	CONSTRAINT pk_follows PRIMARY KEY (follower_id, following_id), 
	CONSTRAINT ck_follows_no_self_follow CHECK (follower_id <> following_id), 
	FOREIGN KEY(follower_id) REFERENCES users (id) ON DELETE CASCADE
);

CREATE TABLE likes (
	id BIGSERIAL NOT NULL, 
	post_id BIGINT NOT NULL, 
	user_id BIGINT NOT NULL, 
	created_at TIMESTAMP WITH TIME ZONE DEFAULT now() NOT NULL, 
	PRIMARY KEY (id), 
	CONSTRAINT uq_likes_post_user UNIQUE (post_id, user_id), 
	FOREIGN KEY(post_id) REFERENCES posts (id) ON DELETE CASCADE
);

CREATE TABLE media (
	id BIGSERIAL NOT NULL, 
	owner_id BIGINT NOT NULL, 
	storage_key VARCHAR(255) NOT NULL, 
	media_type VARCHAR(20) NOT NULL, 
	mime_type VARCHAR(100) NOT NULL, 
	size_bytes BIGINT NOT NULL, 
	created_at TIMESTAMP WITH TIME ZONE DEFAULT now() NOT NULL, 
	PRIMARY KEY (id), 
	CONSTRAINT ck_media_size_nonneg CHECK (size_bytes >= 0), 
	CONSTRAINT ck_media_type CHECK (media_type IN ('image', 'video', 'audio', 'document')), 
	FOREIGN KEY(owner_id) REFERENCES users (id) ON DELETE CASCADE, 
	UNIQUE (storage_key)
);

CREATE TABLE notifications (
	id BIGSERIAL NOT NULL, 
	recipient_id BIGINT NOT NULL, 
	actor_id BIGINT, 
	type VARCHAR(20) NOT NULL, 
	reference_id BIGINT, 
	is_read BOOLEAN NOT NULL, 
	created_at TIMESTAMP WITH TIME ZONE DEFAULT now() NOT NULL, 
	PRIMARY KEY (id), 
	CONSTRAINT ck_notifications_type CHECK (type IN ('like', 'comment', 'follow', 'mention', 'system')), 
	FOREIGN KEY(recipient_id) REFERENCES users (id) ON DELETE CASCADE
);

CREATE TABLE posts (
	id BIGSERIAL NOT NULL, 
	author_id BIGINT NOT NULL, 
	content TEXT NOT NULL, 
	visibility VARCHAR(20) NOT NULL, 
	updated_at TIMESTAMP WITH TIME ZONE DEFAULT now() NOT NULL, 
	created_at TIMESTAMP WITH TIME ZONE DEFAULT now() NOT NULL, 
	PRIMARY KEY (id), 
	CONSTRAINT ck_posts_visibility CHECK (visibility IN ('public', 'private', 'followers')), 
	FOREIGN KEY(author_id) REFERENCES users (id) ON DELETE CASCADE
);

CREATE TABLE profiles (
	id BIGSERIAL NOT NULL, 
	user_id BIGINT NOT NULL, 
	display_name VARCHAR(100) NOT NULL, 
	bio TEXT, 
	avatar_media_id BIGINT, 
	updated_at TIMESTAMP WITH TIME ZONE DEFAULT now() NOT NULL, 
	created_at TIMESTAMP WITH TIME ZONE DEFAULT now() NOT NULL, 
	PRIMARY KEY (id), 
	FOREIGN KEY(user_id) REFERENCES users (id) ON DELETE CASCADE
);

CREATE TABLE users (
	id BIGSERIAL NOT NULL, 
	username VARCHAR(50) NOT NULL, 
	email VARCHAR(254) NOT NULL, 
	password_hash VARCHAR(255) NOT NULL, 
	updated_at TIMESTAMP WITH TIME ZONE DEFAULT now() NOT NULL, 
	created_at TIMESTAMP WITH TIME ZONE DEFAULT now() NOT NULL, 
	PRIMARY KEY (id)
);

CREATE INDEX ix_comments_post_created ON comments (post_id, created_at);

CREATE INDEX ix_comments_user_id ON comments (user_id);

CREATE INDEX ix_follows_following ON follows (following_id);

CREATE INDEX ix_likes_user_id ON likes (user_id);

CREATE INDEX ix_likes_post_id ON likes (post_id);

CREATE INDEX ix_media_owner ON media (owner_id);

CREATE INDEX ix_notifications_recipient_unread ON notifications (recipient_id, is_read);

CREATE INDEX ix_notifications_recipient_created ON notifications (recipient_id, created_at);

CREATE INDEX ix_posts_created_at ON posts (created_at);

CREATE INDEX ix_posts_author_created ON posts (author_id, created_at);

CREATE UNIQUE INDEX ix_profiles_user_id ON profiles (user_id);

CREATE UNIQUE INDEX ix_users_username ON users (username);

CREATE UNIQUE INDEX ix_users_email ON users (email);
